baseURL = "https://endperform.com"
title = "endperform.com"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "console-en"
preserveTaxonomyNames = true

[params]
  [[params.navlinks]]
  name = "/blog"
  url = "archives/"

  [[params.navlinks]]
  name = "/friends"
  url = "friends/"

  [[params.navlinks]]
  name = "/tags"
  url = "tags/"


[permalinks]
    posts = "/:year/:title/"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer] 
unsafe = true
