baseURL = "https://endperform.com"
title = "blog@endperform.com"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "console-en"
preserveTaxonomyNames = true

[params]
  [[params.navlinks]]
  name = "about"
  url = "about/"

  [[params.navlinks]]
  name = "all posts"
  url = "archives/"

  [[params.navlinks]]
  name = "friends"
  url = "friends/"

  [[params.navlinks]]
  name = "tags"
  url = "tags/"


[permalinks]
    posts = "/:title/"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer] 
unsafe = true
